<a href="https://colab.research.google.com/github/MuhamadFaqihBellingh/Projek_Analisis_Data_Faqih/blob/main/ProyekAnalisisDataFaqih.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Proyek Analisis Data: Bike-Sharing-Dataset


*   **Nama:** Muhamad Faqih
*   **Email:**faqihmuh2005@gmail.com
*   **ID Dicoding:** pakihbilekk

# Menentukan Pertanyaan Bisnis


*   Apakah hari kerja atau hari libur lebih mempengaruhi jumlah peminjaman sepeda?
*   Jam Berapa Penggunaan Sepeda Paling Tinggi?

# Import Semua Packages/Library yang Digunakan

In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Data Wrangling

# Gathering Data

In [16]:
df1 = pd.read_csv("/content/day.csv")
df1.head()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,331,654,985
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,131,670,801
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,120,1229,1349
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,108,1454,1562
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,82,1518,1600

In [5]:
import pandas as pd

In [17]:
df2= pd.read_csv("/content/hour.csv", delimiter=";")
df2.head()
#karena masih belum rapih kita pakai format delimeter

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,01/01/2011,1,0,1,0,0,6,0,1,24,2879,81,0,3,13,16
1,2,01/01/2011,1,0,1,1,0,6,0,1,22,2727,8,0,8,32,40
2,3,01/01/2011,1,0,1,2,0,6,0,1,22,2727,8,0,5,27,32
3,4,01/01/2011,1,0,1,3,0,6,0,1,24,2879,75,0,3,10,13
4,5,01/01/2011,1,0,1,4,0,6,0,1,24,2879,75,0,0,1,1

# Insight


*   Membaca dataset menggunakan pandas
*   Menggabungkan data day.csv dan hour.csv dan merapikannya

# Assesing data
**memeriksa data terlebih dahulu sebelum tahap analisis**

In [18]:
df_combined = pd.concat([df1, df2], ignore_index=True)
df_combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18110 entries, 0 to 18109
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     18110 non-null  int64
 1   dteday      18110 non-null  object
 2   season      18110 non-null  int64
 3   yr          18110 non-null  int64
 4   mnth        18110 non-null  int64
 5   holiday     18110 non-null  int64
 6   weekday     18110 non-null  int64
 7   workingday  18110 non-null  int64
 8   weathersit  18110 non-null  int64
 9   temp        18110 non-null  float64
 10  atemp       18110 non-null  float64
 11  hum         18110 non-null  float64
 12  windspeed   18110 non-null  float64
 13  casual      18110 non-null  int64
 14  registered  18110 non-null  int64
 15  cnt         18110 non-null  int64
 16  hr          17379 non-null  float64
dtypes: float64(5), int64(11), object(1)
memory usage: 2.3+ MB

In [30]:
df_combined.isna().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
hr            0
dtype: int64

In [29]:
# Mengganti semua NaN di DataFrame dengan 0
df_combined = df_combined.fillna(0)

In [31]:
print("Jumlah duplikasi: ",df_combined.duplicated().sum())

Jumlah duplikasi:  0

In [32]:
df_combined.describe()

,instant,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt,hr
count,18110.000000,18110.000000,18110.000000,18110.000000,18110.000000,18110.000000,18110.000000,18110.000000,18110.000000,18110.000000,18110.000000,18110.000000,18110.000000,18110.000000,18110.000000,18110.000000
mean,8354.006405,2.501436,0.502485,6.537051,0.028769,3.003424,0.682772,1.424075,37.726677,4115.284912,54.699668,1663.698081,68.472336,295.158697,363.631033,11.080674
std,5180.771860,1.107045,0.500008,3.439213,0.167160,2.005677,0.465410,0.635830,25.791470,2240.263193,26.857410,1337.256015,216.588054,771.555142,950.827954,7.144498
min,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.059130,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
25%,3797.250000,2.000000,0.000000,4.000000,0.000000,1.000000,0.000000,1.000000,8.000000,2576.000000,39.000000,194.000000,4.000000,37.000000,43.000000,5.000000
50%,8324.500000,3.000000,1.000000,7.000000,0.000000,3.000000,1.000000,1.000000,36.000000,4394.000000,58.000000,1343.000000,18.000000,123.000000,152.000000,11.000000
75%,12851.750000,3.000000,1.000000,10.000000,0.000000,5.000000,1.000000,2.000000,62.000000,6061.000000,77.000000,2537.000000,55.000000,238.000000,305.000000,17.000000
max,17379.000000,4.000000,1.000000,12.000000,1.000000,6.000000,1.000000,4.000000,98.000000,9848.000000,97.000000,8507.000000,3410.000000,6946.000000,8714.000000,23.000000

# Insight Assesing Data


*   terdapat 17378 duplikasi pada data gabungan

In [ ]:
#menghapus data duplikat
df_combined.drop_duplicates(inplace=True)

In [33]:
print("Jumlah duplikasi: ", df_combined.duplicated().sum())

Jumlah duplikasi:  0

In [34]:
df_combined.isna().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
hr            0
dtype: int64

# Insight

*   Menghapus duplikasi

# Eksploratory Data Analysis (EDA)

In [ ]:
df_combined.describe(include="all")

         instant      dteday  season   yr  mnth        hr  holiday  weekday  workingday  weathersit       temp        atemp        hum  windspeed    casual  registered        cnt
count   5.000000           5     5.0  5.0   5.0  5.000000      5.0      5.0         5.0         5.0   5.000000     5.000000   5.000000        5.0  5.000000    5.000000   5.000000
unique       NaN           1     NaN  NaN   NaN       NaN      NaN      NaN         NaN         NaN        NaN          NaN        NaN        NaN       NaN         NaN        NaN
top          NaN  01/01/2011     NaN  NaN   NaN       NaN      NaN      NaN         NaN         NaN        NaN          NaN        NaN        NaN       NaN         NaN        NaN
freq         NaN           5     NaN  NaN   NaN       NaN      NaN      NaN         NaN         NaN        NaN          NaN        NaN        NaN       NaN         NaN        NaN
mean    3.000000         NaN     1.0  0.0   1.0  2.000000      0.0      6.0         0.0         1.0  23.200000  2818.200000  49.400000        0.0  3.800000   16.600000  20.400000
std     1.581139         NaN     0.0  0.0   0.0  1.581139      0.0      0.0         0.0         0.0   1.095445    83.253829  37.872153        0.0  2.949576   12.700394  15.565989
min     1.000000         NaN     1.0  0.0   1.0  0.000000      0.0      6.0         0.0         1.0  22.000000  2727.000000   8.000000        0.0  0.000000    1.000000   1.000000
25%     2.000000         NaN     1.0  0.0   1.0  1.000000      0.0      6.0         0.0         1.0  22.000000  2727.000000   8.000000        0.0  3.000000   10.000000  13.000000
50%     3.000000         NaN     1.0  0.0   1.0  2.000000      0.0      6.0         0.0         1.0  24.000000  2879.000000  75.000000        0.0  3.000000   13.000000  16.000000
75%     4.000000         NaN     1.0  0.0   1.0  3.000000      0.0      6.0         0.0         1.0  24.000000  2879.000000  75.000000        0.0  5.000000   27.000000  32.000000
max     5.000000         NaN     1.0  0.0   1.0  4.000000      0.0      6.0         0.0         1.0  24.000000  2879.000000  81.000000        0.0  8.000000   32.000000  40.000000

In [35]:
print("\nDistribusi Nilai Unik Kolom Kategori:")
for col in ['season', 'yr', 'mnth', 'holiday', 'weekday', 'workingday', 'weathersit']:
    value_counts = df_combined[col].value_counts()
    print(f"\nKolom: {col}")
    print(value_counts)

Distribusi Nilai Unik Kolom Kategori:

Kolom: season
season
3    4684
2    4593
1    4423
4    4410
Name: count, dtype: int64

Kolom: yr
yr
1    9100
0    9010
Name: count, dtype: int64

Kolom: mnth
mnth
5     1550
7     1550
12    1545
8     1537
3     1535
10    1513
6     1500
4     1497
9     1497
11    1497
1     1491
2     1398
Name: count, dtype: int64

Kolom: holiday
holiday
0    17589
1      521
Name: count, dtype: int64

Kolom: weekday
weekday
6    2617
0    2607
5    2591
1    2584
3    2579
4    2575
2    2557
Name: count, dtype: int64

Kolom: workingday
workingday
1    12365
0     5745
Name: count, dtype: int64

Kolom: weathersit
weathersit
1    11876
2     4791
3     1440
4        3
Name: count, dtype: int64

In [36]:
#mencari nilai korelasi
print("\nKorelasi Antar Variabel Numerik:")
correlation_matrix = df_combined.select_dtypes(include=['int64', 'float64']).corr()
print(correlation_matrix)

Korelasi Antar Variabel Numerik:
             instant    season        yr      mnth   holiday   weekday  \
instant     1.000000  0.376402  0.806448  0.455668  0.013725  0.001460
season      0.376402  1.000000 -0.010382  0.830429 -0.009623 -0.002365
yr          0.806448 -0.010382  1.000000 -0.010121  0.006743 -0.004524
mnth        0.455668  0.830429 -0.010121  1.000000  0.018461  0.010365
holiday     0.013725 -0.009623  0.006743  0.018461  1.000000 -0.102083
weekday     0.001460 -0.002365 -0.004524  0.010365 -0.102083  1.000000
workingday -0.003352  0.013692 -0.002189 -0.003576 -0.252494  0.035948
weathersit -0.010367 -0.013339 -0.020163  0.006728 -0.017635  0.004274
temp        0.166825  0.172294  0.021508  0.115055 -0.010347  0.004972
atemp       0.219401  0.210485  0.038840  0.141207 -0.037398  0.004909
hum         0.164953  0.130626 -0.030668  0.125286  0.001616 -0.035471
windspeed   0.015301 -0.131722 -0.011412 -0.115569  0.008220  0.004849
casual     -0.198562  0.052572  0.062429  0.029972  0.013794  0.014338
registered -0.228920  0.065660  0.095572  0.046111 -0.017822  0.008174
cnt        -0.230989  0.065255  0.091773  0.044245 -0.011320  0.009899
hr          0.096296 -0.005394 -0.003356 -0.005033  0.000461 -0.003048

            workingday  weathersit      temp     atemp       hum  windspeed  \
instant      -0.003352   -0.010367  0.166825  0.219401  0.164953   0.015301
season        0.013692   -0.013339  0.172294  0.210485  0.130626  -0.131722
yr           -0.002189   -0.020163  0.021508  0.038840 -0.030668  -0.011412
mnth         -0.003576    0.006728  0.115055  0.141207  0.125286  -0.115569
holiday      -0.252494   -0.017635 -0.010347 -0.037398  0.001616   0.008220
weekday       0.035948    0.004274  0.004972  0.004909 -0.035471   0.004849
workingday    1.000000    0.045217  0.024909  0.038490  0.011070  -0.011820
weathersit    0.045217    1.000000 -0.052300 -0.067678  0.236149   0.024295
temp          0.024909   -0.052300  1.000000  0.423925  0.141408   0.059578
atemp         0.038490   -0.067678  0.423925  1.000000  0.194708   0.037640
hum           0.011070    0.236149  0.141408  0.194708  1.000000  -0.053973
windspeed    -0.011820    0.024295  0.059578  0.037640 -0.053973   1.000000
casual       -0.131526   -0.067458 -0.160609 -0.210535 -0.349494  -0.171298
registered    0.050534   -0.049368 -0.229907 -0.293788 -0.398688  -0.215156
cnt           0.011046   -0.055426 -0.223144 -0.286354 -0.403129  -0.213609
hr            0.001951   -0.015919  0.164686  0.199171 -0.025599   0.192276

              casual  registered       cnt        hr
instant    -0.198562   -0.228920 -0.230989  0.096296
season      0.052572    0.065660  0.065255 -0.005394
yr          0.062429    0.095572  0.091773 -0.003356
mnth        0.029972    0.046111  0.044245 -0.005033
holiday     0.013794   -0.017822 -0.011320  0.000461
weekday     0.014338    0.008174  0.009899 -0.003048
workingday -0.131526    0.050534  0.011046  0.001951
weathersit -0.067458   -0.049368 -0.055426 -0.015919
temp       -0.160609   -0.229907 -0.223144  0.164686
atemp      -0.210535   -0.293788 -0.286354  0.199171
hum        -0.349494   -0.398688 -0.403129 -0.025599
windspeed  -0.171298   -0.215156 -0.213609  0.192276
casual      1.000000    0.783516  0.863578 -0.171179
registered  0.783516    1.000000  0.989932 -0.216029
cnt         0.863578    0.989932  1.000000 -0.214291
hr         -0.171179   -0.216029 -0.214291  1.000000

In [37]:
# Menghitung rata-rata peminjaman sepeda berdasarkan hari kerja dan hari libur
avg_casual_by_holiday = df_combined.groupby('holiday')['casual'].mean()
avg_registered_by_holiday = df_combined.groupby('holiday')['registered'].mean()
print("\nRata-rata Peminjaman Sepeda Berdasarkan Hari Kerja dan Hari Libur:")
print(avg_casual_by_holiday)
print(avg_registered_by_holiday)

Rata-rata Peminjaman Sepeda Berdasarkan Hari Kerja dan Hari Libur:
holiday
0    67.958156
1    85.831094
Name: casual, dtype: float64
holiday
0    297.525271
1    215.262956
Name: registered, dtype: float64

In [ ]:
# Mengelompokkan data berdasarkan jam dan menghitung rata-rata jumlah pengguna
avg_casual_by_hour = df_combined.groupby('hr')['casual'].mean()
avg_registered_by_hour = df_combined.groupby('hr')['registered'].mean()
print("\nRata-rata Peminjaman Sepeda Berdasarkan Jam:")
print(avg_casual_by_hour)
print(avg_registered_by_hour)

Rata-rata Peminjaman Sepeda Berdasarkan Jam:
hr
0.0    3.0
1.0    8.0
2.0    5.0
3.0    3.0
4.0    0.0
Name: casual, dtype: float64
hr
0.0    13.0
1.0    32.0
2.0    27.0
3.0    10.0
4.0     1.0
Name: registered, dtype: float64

In [ ]:
df_combined.to_csv("all_data.csv", index=False)
# Changed 'all_df' to 'df_combined' since 'all_df' was not defined.

# Insight


*   menjawab pertanyaan bisnis 1 dan 2

# Conclusion


*   Pengaruh Hari Kerja dan Libur: Terdapat perbedaan dalam jumlah peminjaman sepeda antara hari kerja dan hari libur. Jika peminjaman lebih tinggi pada hari libur, operator dapat memanfaatkan strategi untuk meningkatkan penggunaan sepeda pada hari kerja, seperti penawaran diskon khusus atau insentif bagi pengguna pada hari-hari tersebut.